#!/usr/bin/python2

import sys
import logtail4 as LT

fin, fout, count = sys.argv[1:]
count = int(count)

lines = LT.get_lines(fin, 0)  # Keep all lines in memory
topic = LT.get_topic(lines)
ss = LT.message_pipeline(lines[-count:])  # But only parse last few lines
LT.generate_file(topic, ss, fout)
